# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tugas4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Title Label
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 450, 50))  # Lebih lebar dan lebih tinggi
        font = QtGui.QFont()
        font.setPointSize(12)  # Ukuran font diperkecil agar tidak terpotong
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Product Dropdown
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 110, 71, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 110, 231, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems([
            "Bimoli (Rp. 20,000)",
            "Beras 5 Kg (Rp. 75,000)",
            "Kecap ABC (Rp. 7,000)",
            "Saos Saset (Rp. 2,500)"
        ])
        
        # Quantity Input
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 160, 81, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(330, 160, 91, 21))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        
        # Discount Dropdown
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 220, 81, 21))
        self.label_4.setObjectName("label_4")
        self.discountBox = QtWidgets.QComboBox(self.centralwidget)
        self.discountBox.setGeometry(QtCore.QRect(330, 220, 91, 21))
        self.discountBox.addItems(["0%", "5%", "10%", "15%", "20%"])
        
        # Buttons
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 300, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addToCart)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 300, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clearForm)
        
        # Cart Display
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(130, 360, 621, 121))
        self.listWidget.setObjectName("listWidget")
        
        # Total Price Label
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 490, 311, 21))
        self.label_5.setObjectName("label_5")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Week4"))
        self.label.setText(_translate("MainWindow", "Arnetha Nirwana Putri_F1D022113"))
        self.label_2.setText(_translate("MainWindow", "Product"))
        self.label_3.setText(_translate("MainWindow", "Quantity"))
        self.label_4.setText(_translate("MainWindow", "Discount"))
        self.pushButton.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.label_5.setText(_translate("MainWindow", "Total: Rp 0"))
    
    def addToCart(self):
        products = {
            "Bimoli (Rp. 20,000)": 20000,
            "Beras 5 Kg (Rp. 75,000)": 75000,
            "Kecap ABC (Rp. 7,000)": 7000,
            "Saos Saset (Rp. 2,500)": 2500
        }
        
        product_name = self.comboBox.currentText()
        price = products[product_name]
        quantity = self.spinBox.value()
        discount = int(self.discountBox.currentText().strip('%'))
        
        total_price = price * quantity
        discount_amount = total_price * (discount / 100)
        final_price = total_price - discount_amount
        
        self.listWidget.addItem(f"{product_name} - {quantity} pcs - Discount {discount}% - Total: Rp {final_price:,.2f}")
        
        current_total = float(self.label_5.text().replace("Total: Rp ", "").replace(",", ""))
        new_total = current_total + final_price
        self.label_5.setText(f"Total: Rp {new_total:,.2f}")
    
    def clearForm(self):
        self.comboBox.setCurrentIndex(0)
        self.spinBox.setValue(1)
        self.discountBox.setCurrentIndex(0)
        self.listWidget.clear()
        self.label_5.setText("Total: Rp 0")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())